name: 'Self-hosted kubeseal'
description: 'Download, cache and install the kubeseal to the workspace'
author: 'alexnorell'
inputs:
  release:
    description: 'Version of the kubeseal that should be installed'
    required: false
    default: '0.20.2'
  arch:
    description: 'Architecture to download and install'
    required: false
    default: 'amd64'
  platform:
    description: 'Platform to download and install'  
    required: false
    default: 'linux'
runs:
  using: 'node16'
  main: 'dist/index.js'
